name: SMS Notification 


on:
  workflow_run:
    workflows: [ "Docker Image Publish", "Docker Compose Actions Workflow", "Python Application Test"]
    branches: [dev, main]
    types:
      - completed

  workflow_dispatch:

jobs:

 build:
  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v5

  - name: SMS Notification
    if: ${{ github.event.workflow_run.conclusion == 'failure' || github.event.workflow_run.conclusion == 'cancelled' }}
    uses: alphaolomi/actions-africastalking@main
    with:
      fromPhoneNumber: 'INFO'   # or  ${{ secrets.fromPhoneNumber }}
      toPhoneNumber: ${{ secrets.toPhoneNumber }}
      message: ${{ github.event_name }} on ${{ github.repository }} by ${{ github.actor }} has ${{github.event.workflow_run.conclusion}}. Check it out at ${{ github.event.workflow_run.url }}
    env:
      AT_API_KEY: ${{ secrets.AT_API_KEY }}
      AT_USERNAME: ${{ secrets.AT_USERNAME }}
